<?php
/**
 * Acaldeira Mercadolivre 
 * 
 * @category     Acaldeira
 * @package      Acaldeira_Mercadolivre 
 * @copyright    Copyright (c) 2015 MM (http://blog.meumagento.com.br/)
 * @author       MM (Thiago Caldeira de Lima)  
 * @version      Release: 0.1.0 
 */
?>
<?php 
    $order = $this->getOrder();
    $content = $order['body'];
?>


<div class="content-header">
    <h3 class="icon-head head-sales-order">
    <?php echo Mage::helper('mercadolivre')->__("MercadoLivre Order #%s",$content->id); ?></h3>
</div>


<div class="entry-edit" id="sales_order_view">
    <div id="sales_order_view_tabs_order_info_content">
        <div>
            <div id="order-messages"></div>
            <div class="box-left">
            <!--Order Information-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-account">Pedido</h4>
                    </div>
                    <div class="fieldset">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label"><label>Data do Pedido</label></td>
                                    <td class="value"><strong><?php echo $content->date_created;?> </strong></td>
                                </tr>
                                <tr>
                                    <td class="label"><label>Status do Pedido</label></td>
                                    <td class="value"><strong><span id="order_status"><?php echo $content->status;?></span></strong></td>
                                </tr>

                                <tr>
                                    <td class="label"><label>Tags</label></td>
                                    <td class="value"><strong><span id="order_status"><?php echo implode(",", $content->tags);?></span></strong></td>
                                </tr>
                             </tbody>
                         </table>
                    </div>
                </div>
            </div>
            <div class="box-right">
                <!--Account Information-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-account">Informações da Conta</h4>
                        <div class="tools"></div>
                    </div>
                    <div class="fieldset">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                    <tr>
                                        <td class="label"><label>MLID</label></td>
                                        <td class="value"><strong><?php echo $content->buyer->nickname;?></strong></td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>Nome do Cliente</label></td>
                                        <td class="value">
                                               <strong><?php echo $content->buyer->first_name;?> <?php echo $content->buyer->last_name;?></strong>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label>Email</label></td>
                                        <td class="value"><a href="mailto:<?php echo $content->buyer->email;?>"><strong><?php echo $content->buyer->email;?></strong></a></td>
                                    </tr>
                                 </tbody>
                             </table>
                        </div>
                    </div>
                </div>
            </div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address">Informações do Vendedor</h4>
            <div class="tools"></div>
        </div>
        <fieldset>
            <address>
                <?php echo Mage::helper('mercadolivre')->__("ID");?>: <?php echo $content->seller->id;?> <br>
            <?php echo Mage::helper('mercadolivre')->__("Nickname");?>: <?php echo $content->seller->nickname;?> <br>
            <?php echo Mage::helper('mercadolivre')->__("Email");?>: <?php echo $content->seller->email;?> <br>
            <?php echo Mage::helper('mercadolivre')->__("Phone");?>: 
            (<?php echo $content->seller->phone->area_code;?>) <?php echo $content->seller->phone->number;?>  ext: <?php echo $content->seller->phone->extension;?>  <br>
            <?php echo Mage::helper('mercadolivre')->__("Name");?>: <?php echo $content->seller->first_name;?> <?php echo $content->seller->last_name;?> <br>
            </address>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address">Dados para Entrega</h4>
            <div class="tools"></div>
        </div>
        <fieldset>
            <?php echo Mage::helper('mercadolivre')->__("ID");?>: <?php echo $content->shipping->id;?> <br>
            <?php echo Mage::helper('mercadolivre')->__("Type");?>: <?php echo $content->shipping->shipment_type;?> <br>
            <?php echo Mage::helper('mercadolivre')->__("Status");?>: <?php echo $content->shipping->status;?> <br>
            <?php echo Mage::helper('mercadolivre')->__("Date");?>: <?php echo $content->shipping->date_created;?> <br>
            <strong>Endereço</strong>
            <address>
                <?php echo $content->shipping->receiver_address->street_name;?>, <?php echo $content->shipping->receiver_address->street_number;?>  <?php echo $content->shipping->receiver_address->comment;?><br>
                <?php echo $content->shipping->receiver_address->city->name;?> <br>
                <?php echo $content->shipping->receiver_address->state->name;?> <br>
                <?php echo $content->shipping->receiver_address->zip_code;?> <br>    
            </address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
    <input type="hidden" name="order_id" value="1814">
        <div class="box-left">
            <!--Payment Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method">Informações de Pagamento</h4>
            </div>
            <fieldset>
                <?php foreach ($content->payments as $payment): ?>
                    ID: <?php echo $payment->id;?> <br>
                    Total: <?php echo $payment->transaction_amount;?> <br>
                    Status: <?php echo $payment->status;?> <br>
                    Data: <?php echo $payment->date_created;?> <br>
                    Metodo de Pagamento: <?php echo $payment->payment_method_id;?> <br>
                    <div>Pedido foi feito usando <?php echo $payment->currency_id;?></div>
                <?php endforeach;?>
            </fieldset>
        </div>
    </div>
        <div class="box-right">
        <!--Shipping Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-method">Informações de Frete &amp; Manuseio</h4>
            </div>
            <fieldset>

                <strong><?php echo $content->shipping->shipment_type;?></strong>                                                                        
                <span class="price">R$ <?php echo $content->shipping->cost;?></span>                                                
            </fieldset>
        </div>
    </div>
        <div class="clear"></div>
        <div class="clear"></div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products">Itens Adquiridos</h4>
        </div>
    </div>
    <div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <thead>
            <tr class="headings">
                <th>Produto</th>
                <th>Preço</th>
                <th class="a-center">Qtd</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody class="even">
            
        <?php 
            foreach ($content->order_items as $item): 
                $_subtotal = $item->unit_price*$item->quantity;
        ?>
            <tr class="border">
                <td>
                    <div id="order_item_2186" class="item-container">
                        <div class="item-text">
                            <h5 class="title">
                                <span id="order_item_2186_title">
                                    <?php echo $item->item->title;?>
                                </span>
                            </h5>
                            <div>
                                <strong>MLID:</strong> <?php echo $item->item->id?>
                            </div>
                        </div>
                    </div>
                </td>
   
                <td class="a-right"><span class="price"><?php echo $item->currency_id;?> <?php echo $item->unit_price;?></span></td>
                <td class="a-right">
                    <span class="qty">
                        <span class="qty"><?php echo $item->quantity;?></span>                
                    </span>
                    <br>
                </td>
                <td class="a-right">
                    <span class="price-excl-tax">
                        <span class="price"><?php echo $item->currency_id;?> <?php echo $_subtotal?></span>                
                    </span>
                    <br>
                </td>
        
            </tr>
           <?php
                $subtotal+=$_subtotal;
                endforeach;
           ?>         
        </tbody>
    </table>
  </div>
</div>
<br>   
<div class="clear"></div>
</div>
</fieldset>
        </div>
    </div>
    <div class="box-right entry-edit">
        <div class="entry-edit-head"><h4>Totais do Pedido</h4></div>
        <div class="order-totals">
            <table cellspacing="0" width="100%">
                <tfoot>
                    <tr class="0">
                        <td class="label">
                            <strong>Total Geral</strong>
                        </td>
                        <td class="emph">
                            <strong><span class="price"><?php echo $content->currency_id;?> <?php echo $content->total_amount;?></span></strong>
                        </td>
                    </tr>   
                </tfoot>
                <tbody>
                    <tr class="0">
                        <td class="label">
                            Subtotal                            
                        </td>
                        <td>
                            <span class="price"><?php echo $content->currency_id;?> <?php echo $subtotal;?></span>                        
                        </td>
                    </tr>
                    <tr class="1">
                        <td class="label">
                            Frete &amp; Manuseio                            
                        </td>
                        <td>
                            <span class="price"><?php echo $content->currency_id;?> <?php echo $content->shipping->cost;?></span>                        
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
   
</div>