<?php
/**
 * Acaldeira Mercadolivre 
 * 
 * @category     Acaldeira
 * @package      Acaldeira_Mercadolivre 
 * @copyright    Copyright (c) 2015 MM (http://blog.meumagento.com.br/)
 * @author       MM (Thiago Caldeira de Lima)  
 * @version      Release: 0.1.0 
 */
?>
<?php if(!$this->isLogged()): ?>

    <a href="<?php echo $this->getLoginUrl();?>"><?php echo __('Login')?></a>

<?php else: ?> 

    Logado.

<?php endif;?>

